### ISSUE TITLE
exception while saving paths file in train_integrated.py

### ISSUE THREAD

**Issue by isimova** [vered1986/LexNET#3]
Hello,

I encounter an exception while training an integrated LexNet model (branch V2). Saving the paths file fails with:

    Traceback (most recent call last):
      File "train_integrated.py", line 209, in <module>
        main()
      File "train_integrated.py", line 128, in main
        top_k = classifier.get_top_k_paths(all_paths, relation_index, 0.7)
      File "/local/LexNET/train/paths_lstm_classifier.py", line 196, in get_top_k_paths
        if threshold is None or path_scores[index, i] >= threshold])
    IndexError: list index out of range

Full log is attached. 
[lexnet_train_V2.log](https://github.com/vered1986/LexNET/files/1695049/lexnet_train_V2.log)

**Comment by vered1986** [comment]
Fixed, thanks @isimova!
