### ISSUE TITLE
exception while testing with test_integrated.py

### ISSUE THREAD

**Issue by isimova** [vered1986/LexNET#4]
Hello,

the following exception occurs when running test_integrated.py

    Traceback (most recent call last)
      File "test_integrated.py", line 12, in <module>
        from paths_lstm_classifier import *
      File "/local/LexNET/train/paths_lstm_classifier.py", line 3, in <module>
        from __main__ import args
      ImportError: cannot import name args

Thanks!

**Comment by vered1986** [comment]
Fixed, thanks @isimova!
